[package]
name = "reader"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version = "0.4.40", features = ["serde"]}
serde = { version = "1.0.219", features = ["derive"] }
csv = "*"

[[test]]
name = "reader_tests"
path = "test/reader_test.rs"